#pragma once

#include <vector>
#include <string>
#include <cctype>
#include <map>
#include <unordered_map>
#include <variant>
#include <iostream>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stack>
#include <memory>
#include <functional>
#include <random>
#include <any>
#include <algorithm>
#include "MagicEnum.hpp"