#pragma once

#include <iostream>
#include <fstream>
#include <string>
#include <filesystem>
#include <chrono>
#include <thread>
#include <random>
#include <cstdlib>
#include <windows.h>
#include <algorithm>
#include <vector>
#include <regex>
#include <cctype>
#include <optional>
#include <utility>
#include <sstream>
#include <any>
#include <variant>
#include <stdexcept>
#include <cstdlib>
#include <typeinfo>
#include <unordered_map>
#include <cstring>
#include <stack>
#include <cmath>
#include <iomanip>
#include <unordered_set>

using std::any;
using std::any_cast;
using std::cin;
using std::cout;
using std::endl;
using std::ifstream;
using std::max;
using std::pair;
using std::string;
using std::stringstream;
using std::unordered_map;
using std::vector;